// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrBO7GFl1ZRLzp_LmNCxRyJAgA1wZFQk',
    appId: '1:347739508238:web:6274ff0839f54baa9d365f',
    messagingSenderId: '347739508238',
    projectId: 'socialapp-95f6c',
    authDomain: 'socialapp-95f6c.firebaseapp.com',
    databaseURL: 'https://socialapp-95f6c-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-95f6c.appspot.com',
    measurementId: 'G-RJDCL1DVBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_t3q3od2hSv_BIP6GkB-5Cfs90VhhNCQ',
    appId: '1:347739508238:android:3840f3af38643fd79d365f',
    messagingSenderId: '347739508238',
    projectId: 'socialapp-95f6c',
    databaseURL: 'https://socialapp-95f6c-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-95f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKdYZl-95nJAEN04G_UuWxVj0_WQIh9RQ',
    appId: '1:347739508238:ios:d2350312a3dc4ae99d365f',
    messagingSenderId: '347739508238',
    projectId: 'socialapp-95f6c',
    databaseURL: 'https://socialapp-95f6c-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-95f6c.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKdYZl-95nJAEN04G_UuWxVj0_WQIh9RQ',
    appId: '1:347739508238:ios:954c5e8701e297539d365f',
    messagingSenderId: '347739508238',
    projectId: 'socialapp-95f6c',
    databaseURL: 'https://socialapp-95f6c-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-95f6c.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
